name: CI Develop Branch

on:
  push:
    branches:    
      - 'dev'

jobs:
  unit-test-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm test
    - uses: codecov/codecov-action@v2
  unit-test-restapi:
    runs-on: ubuntu-latest
    env:
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      SECRET_SALT: ${{ secrets.SECRET_SALT }}
      SECRET: ${{ secrets.SECRET }}
      PRUEBA: ${{ secrets.PRUEBA }}
    defaults:
      run:
        working-directory: restapi
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm test
    - uses: codecov/codecov-action@v2
  # e2e-tests:
  #   needs: [unit-test-webapp, unit-test-restapi]
  #   runs-on: ubuntu-latest
  #   env:
  #     MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
  #     SECRET_SALT: ${{ secrets.SECRET_SALT }}
  #     SECRET: ${{ secrets.SECRET }}
  #     PRUEBA: ${{ secrets.PRUEBA }}
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: 16
  #   - run: npm --prefix webapp install
  #   - run: npm --prefix restapi install
  #   - run: npm --prefix webapp run build
  #   - run: npm --prefix webapp run test:e2e